import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#EDEDED" },
  scrollContainer: {
    padding: 24,
    alignItems: "center",
    justifyContent: "center",
    minHeight: "100%",
  },
  logo: { width: 160, height: 50, marginBottom: 30, marginTop: 20 },
  image: { width: 220, height: 220, marginBottom: 20 },
  description: {
    fontSize: 22,
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 30,
    color: "#333",
  },
  inputArea: { width: "100%" },
  customInput: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFF",
    padding: 15,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: "#DDD",
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  inputText: { flex: 1, fontSize: 14, color: "#000" },
  orText: {
    textAlign: "center",
    marginVertical: 20,
    color: "#777",
    fontSize: 14,
  },
  buttonWrapper: { width: "100%", alignItems: "center" },

  bottomSheetOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "flex-end",
  },
  bottomSheetContent: {
    backgroundColor: "#FFF",
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    padding: 20,
    height: "85%",
  },
  handleBar: {
    width: 40,
    height: 5,
    backgroundColor: "#EEE",
    borderRadius: 10,
    alignSelf: "center",
    marginBottom: 15,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  modalTitle: { fontSize: 20, fontWeight: "bold", color: "#333" },
  searchBarContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F5F5F5",
    borderRadius: 12,
    marginBottom: 20,
  },
  modalInput: { flex: 1, padding: 12, fontSize: 15 },
  locationCard: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#F9F9F9",
  },
  iconCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#E8F4F8",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 15,
  },
  locName: { fontSize: 16, fontWeight: "bold", color: "#333" },
  locDesc: { fontSize: 12, color: "#888", marginTop: 2 },

  gpsButton: {
  backgroundColor: "#1E6F9F",
  borderRadius: 12,
  paddingVertical: 14,
  paddingHorizontal: 24,
  width: "100%",
  alignItems: "center",
},
gpsButtonLoading: {
  backgroundColor: "#155a80",
  opacity: 0.9,
},
gpsButtonInner: {
  flexDirection: "row",
  alignItems: "center",
  gap: 8,
},
gpsButtonText: {
  color: "#ffffff",
  fontSize: 16,
  fontWeight: "600",
},
});
